### ISSUE TITLE
replace IAC API with rp API

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/contacts-sync-prototype#1]

**Comment by jaredhirsch** [comment]
taking this

**Comment by jaredhirsch** [comment]
le sigh, took wrong one

**Comment by carlosdp** [comment]
Done!

**Comment by jaredhirsch** [comment]
cool, if it's done, open a PR with the code and a "fixes #1" in the commit message, let's get the code into the repo :-)

**Comment by jaredhirsch** [comment]
well actually...let's get through the demo this week, and worry about cleanup later :-)
